name: Build and Upload

on:
  push:
    branches: [ master, release/*, feature/* ]
  pull_request:
    branches: [ master, release/*, feature/* ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      INSTALL_DIR: "/tmp/binutils"

    steps:
    - uses: actions/checkout@v2

    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgmp-dev libmpfr-dev

    - name: Extract tag name
      id: extract_tag
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Configure
      run: |
       mkdir $INSTALL_DIR
       mkdir build
       cd build
       ../configure \
          --disable-werror \
          --with-mmap \
          --prefix=$INSTALL_DIR

    - name: Build
      run: |
       cd build
       make
       make install

    - name: Package
      run: |
        tar -czvf omftools-${{ github.run_id }}-${{ github.sha }}-linux-x86_64.tar.gz --transform='s|nm|omf-nm|' --transform='s|objdump|omf-objdump|' -C $INSTALL_DIR/bin nm objdump
        tar -czvf binutils-${{ github.run_id }}-${{ github.sha }}-linux-x86_64.tar.gz -C $INSTALL_DIR bin include lib share
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: binutils-${{ github.run_id }}-${{ github.sha }}-linux-x86_64.tar.gz
        path: ./binutils-${{ github.run_id }}-${{ github.sha }}-linux-x86_64.tar.gz
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: omftools-${{ github.run_id }}-${{ github.sha }}-linux-x86_64.tar.gz
        path: ./omftools-${{ github.run_id }}-${{ github.sha }}-linux-x86_64.tar.gz
